# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cc674ae9d1c1c0f2e3af2971f1857f7d067208a5c327978386bfece83d9ad82e34251777e8e2c09b68bc0593e39ccaf07201e10c9349a93e100965fd488f8a7

test:
  secret_key_base: a2647dbcb7c394bb63299af05cb9844ba6e65fea959fabc9d4514cf4d5c9a4a14ac93c208d8d79341afe36a487db956520f75c7c91af821bef52ac950d9769b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
